const HTTP_OK = 200;
const HTTP_BAD_REQUEST = 400;
const HTTP_INTERNAL_SERVER_ERROR = 500;

const SUCCESS = true;
const FAILED = false;

const SUPER_ADMIN = 1;
const SUB_ADMIN = 2;
const READ_ONLY = 3;

module.exports = {
  HTTP_BAD_REQUEST,
  HTTP_OK,
  SUCCESS,
  FAILED,
  SUB_ADMIN,
  SUPER_ADMIN,
  READ_ONLY,
  HTTP_INTERNAL_SERVER_ERROR,
};
